### ISSUE TITLE
[FR] Download only specific folders/files?

### ISSUE THREAD

**Issue by ghost** [john-corcoran/internetarchive-downloader#1]
Hi! Couldn't find anything about it in the README, so I assume it's not implemented. Could you possibly make this happen?

**Comment by john-corcoran** [comment]
Hi there, you can use the `-f` / `--filefilters` flag while specifying the full filename(s), which should work but doesn't scale that well if you have many filenames. Let me know if that suits your workflow; I had considered also adding a flag to read in a file containing filter filenames, and will prioritise if it helps!

**Comment by ghost** [comment]
I decided to just sort it out manually a few days ago, so I don't really need this script anymore. Thanks for the help though, I suppose your method works, so I'll close the issue now.
