### ISSUE TITLE
The package of Internet Archive Python Library does not work.

### ISSUE THREAD

**Issue by thatonepreservator** [john-corcoran/internetarchive-downloader#15]
I cannot seem to get the tool working because of IA Python Library not working. Any suggestions on how to fix this issue?

**Comment by john-corcoran** [comment]
Hi there, what error message do you get?

**Comment by thatonepreservator** [comment]
It told me that I had to install the Python Library while I had it already
installed

**Comment by john-corcoran** [comment]
Thanks, can you copy and paste the specific error? This will help diagnose if it's a problem with the script itself, or a local configuration issue.

**Comment by thatonepreservator** [comment]
I may do it later

**Comment by john-corcoran** [comment]
(Issue closed due to inactivity)
