### ISSUE TITLE
Inverse filter

### ISSUE THREAD

**Issue by akudaikon** [john-corcoran/internetarchive-downloader#2]
It would be incredibly useful to have an inverse filter that would _not_ download anything that matches it. Just like `-f`/`--filefilters`, but inverted logic. Thanks!

**Comment by john-corcoran** [comment]
Thanks, great idea! Added in [v1.0.4](https://github.com/john-corcoran/internetarchive-downloader/releases/tag/v1.0.4) - set filters as before using `-f`/`--filefilters`, but add an additional boolean argument of `--invertfilefiltering` to change the filtering to only download files that do not match the filters 👍
