### ISSUE TITLE
Is it possible to download an archived page with this?

### ISSUE THREAD

**Issue by ghost** [john-corcoran/internetarchive-downloader#4]
Hello,
Thanks for the project. Is it possible to download an archived page with this? I can't find an identifier for an old page I want to download. Example http://web.archive.org/web/19961219022100/http://x.com/
Thanks!

**Comment by john-corcoran** [comment]
Hi, unfortunately Wayback Machine pages ([web.archive.org](https://web.archive.org/)) aren't supported by this script - I've added a note to the readme to hopefully make this clearer.

I've not tried any scripts for Wayback Machine, but perhaps something like [waybackpack](https://github.com/jsvine/waybackpack) or [waybackpy](https://pypi.org/project/waybackpy/) would assist?
