### ISSUE TITLE
Download all the content uploaded by one user?

### ISSUE THREAD

**Issue by ErikUden** [john-corcoran/internetarchive-downloader#6]
Is it possible to specifically download all the content uploaded by one user using this script?

Just wanted to ask how that would be possible using this script!

Thank you for your help in advance!

EDIT: So, essentially I wanted to download all the freely available podcast episodes from "TrueAnon" found here:
https://archive.org/search.php?query=creator%3A"TrueAnon+Podcast"
They are anti-conspiratorial and debunk a lot of the QAnon rhetoric. I find it very important, other people do so too, hence the archive, however, I wanted to listen to the podcast, so, I need the files locally. I just didn't want to download 270 files manually, so this script came to rescue!

So, how would one download all of these files if what is linking them together is only their search term "TrueAnon Podcast"?

**Comment by john-corcoran** [comment]
Hi, thanks for the note - I think it's possible to download all items associated with any search term, as long as the search term returns a relatively small number of items (testing with a user that has uploaded 18K items throws a `requests.exceptions.ReadTimeout` when trying to iterate `search_results`) - I'll add this in a future version.

Short term fix for your situation would be to change `collection:` to `creator:` in line 917 in the current version (https://github.com/john-corcoran/internetarchive-downloader/blob/022a92773e1f37e957ad391e26337e8985510bc9/ia_downloader.py). Then run `python3 ia_downloader.py download 'creator:"search term"'`

**Comment by john-corcoran** [comment]
Search terms are now supported as of [release v1.1.0](https://github.com/john-corcoran/internetarchive-downloader/releases/tag/v1.1.0).

**Comment by ErikUden** [comment]
This is incredible. You are amazing, will try this out ASAP!
